# Generated by Django 4.1.3 on 2022-11-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
